### PR TITLE
Target .NET Framework 4.6.2

### PR DESCRIPTION
**Pull request by JamieMagee**

### CODE REVIEW

**Comment by LordMike** [comment]
Shouldn't `4.6.2` environments be able to reference this dll - I assume that's the end goal?

If anything. I'd port the project to a .NET core project style, and have that build environment target multiple frameworks, such as core, .NET, netstandard etc.

**Comment by JamieMagee** [comment]
Yeah, I think a .NET core project would also be better. Targeting .netstandard. I'll give that a go and open another pull request for it.

**Comment by LordMike** [comment]
Then target a number of projects. Look at my other project.json file here: https://github.com/LordMike/TMDbLib/blob/master/TMDbLib/project.json

It targets all relevant frameworks, which helps immensely when building nuget packages.

**Comment by JamieMagee** [comment]
I had a look at that, but I don't think it's necessary. Looking at [this chart](https://github.com/dotnet/corefx/blob/master/Documentation/architecture/net-platform-standard.md#mapping-the-net-platform-standard-to-platforms) `netstandard` maps to a lot of different platforms.

**Comment by LordMike** [comment]
I've seen that a few times. I went the safe route as I seem to recall Nuget refusing to install to 4.x projects, because the "package doesn't target that framework". But when inspected, I can clearly see a 4.0 library in the packages.

To me it at least seems like the Nuget client doesn't follow the logic in the above chart. But hey, give it a try and then I could probably clean the TMDbLib project.json up :P.

**Comment by JamieMagee** [comment]
I had a go at this, but currently I don't believe the tooling is great, and the platform is a moving target. [This post](https://blogs.msdn.microsoft.com/dotnet/2016/09/26/introducing-net-standard/) from yesterday just confirms it for me.

**Comment by LordMike** [comment]
Yea. The tooling is nowhere near what we have on the regular .NET framework.

**Comment by JamieMagee** [comment]
Could I suggest keeping the library in its current form, and just bumping the .NET Framework version to v4.6.1. It's mentioned in the blog post I linked above that v4.6.1 is the most popular version on NuGet.

**Comment by LordMike** [comment]
I am not sure why you want the targeting of `4.6.1` (or `4.6.2`). I've just created a .NET `4.6.1` project, and installed the SslLabsLib nuget package without a hitch.

Am I missing something important?

**Comment by JamieMagee** [comment]
Yeah, there's no issues including it in a new project, but there are a lot of new features with newer versions of .NET Framework. [Here's an article](https://blogs.msdn.microsoft.com/dotnet/2015/07/20/announcing-net-framework-4-6/) about .NET Framework 4.6.

I think two features that could be useful are HTTP/2 support, and support for C# 6 language features.

**Comment by LordMike** [comment]
Hi @JamieMagee.

It is my understanding that this is incorrect. As a library, you can include this project anywhere, and still benefit from whatever language features you may want. And should your project use .NET 4.6.x and have features like HTTP/2, my library should then be able to use them. You will reference and include all the System.Core and System.Net assemblies relevant for 4.6.x, which I will then use (they have API compatibility).

So in practice, my library can easily use whatever new feature .NET may come with, if your application is using them.

I will close this now.

**Pull request closed without merging**
